eGonullu/Controllers/MyActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using eGonullu.Filters;
using eGonullu.Models;
using eGonullu.Services;
using eGonullu.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace eGonullu.Controllers
{
	[LoginCheck]
	public class MyActivitiesController : Controller
	{
		private IUserData _userData;
		private IActivityData _activityData;

		public MyActivitiesController(IActivityData activityData, IUserData userData)
		{
			_activityData = activityData;
			_userData = userData;
		}
		public IActionResult Index()
		{
			var viewModel = new ActivityIndexViewModel
			{
				Activities = _activityData.GetUserActivities(getUser().Id)
			};
			return View(viewModel);
		}

		public IActionResult Details(int id)
		{
			var participants = new List<User>();
			foreach (var activityParticipant in _activityData.Get(id).Participants)
			{
				participants.Add(_userData.Get(activityParticipant.UserId).Result);
			}
			var viewModel = new ActivityDetailsViewModel
			{
				Activity = _activityData.Get(id),
				ActivityUser = getUser(),
				Participants = participants
			};
			return View(viewModel);
		}

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(ActivityEditViewModel model)
		{
			if (ModelState.IsValid)
			{
				var activity = new Activity
				{
					UserId = getUser().Id,
					ActivityDate = model.ActivityDate,
					AddressDetail = model.AddressDetail,
					Title = model.Title,
					City = model.City,
					State = model.State,
					Name = model.Name,
					Definition = model.Definition,
					PictureUrl = model.PictureUrl
				};
				activity = _activityData.Add(activity);
				return RedirectToAction(nameof(Details), new { id = activity.Id });
			}
			else
			{
				return View();
			}
		}

		[HttpGet("[controller]/[action]/{id}")]
		public IActionResult Edit(int id)
		{
			return View(_activityData.Get(id));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Activity activity)
		{
			if (getUser().Id != activity.UserId)
			{
				return RedirectToAction("Index", "Home");
			}
			if (ModelState.IsValid)
			{
				_activityData.Update(activity);
				return RedirectToAction(nameof(Details), new { id = activity.Id });
			}
			else
			{
				return View();
			}
		}
		
		private User getUser()
		{
			var userId = HttpContext.Session.GetInt32("userId").GetValueOrDefault();
			return _userData.Get(userId).Result;
		}
	}
}

eGonullu/Controllers/MyActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using eGonullu.Models;
using eGonullu.Services;
using eGonullu.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace eGonullu.Controllers
{
	public class MyActivityController : Controller
	{
		private IUserData _userData;
		private IActivityData _activityData;

		public MyActivityController(IActivityData activityData, IUserData userData)
		{
			_activityData = activityData;
			_userData = userData;
		}
		public IActionResult Index()
		{
			var viewModel = new ActivityIndexViewModel
			{
				Activities = _activityData.GetUserActivities(getUser().Id)
			};
			return View(viewModel);
		}

		public IActionResult Details(int id)
		{
			var viewModel = new ActivityDetailsViewModel
			{
				Activity = _activityData.Get(id)
			};
			return View(viewModel);
		}

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(ActivityEditViewModel model)
		{
			if (ModelState.IsValid)
			{
				var activity = new Activity
				{
					User = getUser(),
					ActivityDate = model.ActivityDate,
					City = model.City,
					State = model.State,
					Name = model.Name,
					Definition = model.Definition,
					PictureUrl = model.PictureUrl
				};
				activity = _activityData.Add(activity);
				return RedirectToAction(nameof(Details), new { id = activity.Id });
			}
			else
			{
				return View();
			}
		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
			return View(_activityData.Get(id));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Activity activity)
		{
			if (ModelState.IsValid)
			{
				_activityData.Update(activity);
				return RedirectToAction(nameof(Details), new { id = activity.Id });
			}
			else
			{
				return View();
			}
		}

		private User getUser()
		{
			return _userData.GetUserByClaims(User.Claims);
		}
	}
}

eGonullu/Views/MyActivities/Create.cshtml
@using eGonullu.Data
@model Activity
@{
    var cities = new List<SelectListItem>();
    CityStateData.GetCities().ForEach(c =>
    {
        cities.Add(new SelectListItem(c, c));
    });
}
<div class="container">
    <div class="m-3"></div>
    <div class="main-body">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-5">
                <div class="row m-5"></div>w
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="/images/activity.png" alt="Admin" class="rounded-top" width="360">
                            <div class="mt-3">
                                <p class="text-secondary mb-1">Etkinlikle İlgili Kapak Forografı Yükleyin.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-8">

                <form method="post">
                    <div class="row m-3"><h4>Etkinlik Oluştur</h4></div>
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Etkinlik Adı</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="Name" class="form-control form-control-sm" placeholder="Etkinliğin Adı" />
                                    <span asp-validation-for="Name"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Başlık</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="Title" class="form-control form-control-sm" placeholder="Başlık" />
                                    <span asp-validation-for="Title"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">İl</h6>
                                </div>
                                <div class="col-sm-9">
                                    <select asp-for="City" class="form-control form-control-sm" asp-items="cities">
                                    </select>
                                    <span asp-validation-for="Name"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">İlçe</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="State" class="form-control form-control-sm" placeholder="İlçe" />
                                    <span asp-validation-for="State"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Adres</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="AddressDetail" class="form-control form-control-sm" placeholder="İlçe" />
                                    <span asp-validation-for="AddressDetail"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Etkinlik Tarihi</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="ActivityDate" class="form-control form-control-sm" />
                                    <span asp-validation-for="ActivityDate"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Fotoğraf</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="PictureUrl" class="form-control form-control-sm" placeholder="Kapak Fotoğrafı için URL Ekleyin." />
                                    <span asp-validation-for="PictureUrl"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Açıklama</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="Definition" class="form-control" />
                                    <span asp-validation-for="Definition"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-9">
                        <input class="btn btn-outline-success" type="submit" name="save" value="Kaydet" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

eGonullu/Views/MyActivities/Details.cshtml
@model eGonullu.ViewModels.ActivityDetailsViewModel


<div class="container">
    <div class="m-3"></div>
    <div class="main-body">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="row m-3"><h4 style="color:white">.</h4></div>
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="@Model.Activity.PictureUrl" alt="Admin" class="rounded-top" width="330" height="425">
                            <div class="mt-3">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="row m-3"><h4>@Model.Activity.Title</h4></div>
                <div class="card mb-3">
                    <div class="card-body">

                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Etkinlik Adı: </h6>
                            </div>
                            <div class="col-sm-9">
                                <p>@Model.Activity.Name</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">İl: </h6>
                            </div>
                            <div class="col-sm-9">
                                <p>@Model.Activity.City</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">İlçe: </h6>
                            </div>
                            <div class="col-sm-9">
                                <p>@Model.Activity.State</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Adres: </h6>
                            </div>
                            <div class="col-sm-9">
                                <p>@Model.Activity.AddressDetail</p>
                            </div>
                        </div>
                        <hr>

                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Etkinlik Tarihi: </h6>
                            </div>
                            <div class="col-sm-9">
                                <p>@Model.Activity.ActivityDate.ToLongDateString()</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Detay: </h6>
                            </div>
                            <div class="col-sm-9">
                                <p>
                                    @Model.Activity.Definition
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="btn btn-outline-success" asp-action="Edit" asp-route-id="@Model.Activity.Id">Düzenle</a>
            </div>
        </div>
        <hr />
        <div class="m-2" style="text-align:center"><h3>Gönüllüler </h3><hr /></div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4 gutters-sm">


            @if (Model.Participants.Any())
            {
                foreach (var participant in Model.Participants)
                {
                    <div class="col-md-4">
                        <div class="card profile-card-1">
                            <img src="@participant.PictureUrl" alt="profile-sample1" class="background" />
                            <img src="@participant.PictureUrl" alt="profile-image" class="profile" />
                            <div class="card-content">
                                <h3><small>@participant.Name</small></h3>
                                <h2>@participant.LastName</h2>
                                <div class="icon-block">
                                    <a href="@participant.Facebook" target="_blank"><i class="fa fa-facebook"></i></a>
                                    <a href="@participant.Twitter" target="_blank"> <i class="fa fa-twitter"></i></a>
                                    <a href="@participant.Instagram" target="_blank"> <i class="fa fa-instagram"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }

        </div>
    </div>
</div>

eGonullu/Views/MyActivities/Edit.cshtml
@using eGonullu.Data
@model Activity
@{
    var cities = new List<SelectListItem>();
    CityStateData.GetCities().ForEach(c =>
    {
        cities.Add(new SelectListItem(c, c));
    });
}
<div class="container">
    <div class="m-3"></div>
    <div class="main-body">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="row m-3"><h4 style="color:white">.</h4></div>
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="@Model.PictureUrl" alt="Admin" class="rounded-top" width="330" height="425">
                            <div class="mt-3">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-8">

                <form method="post">
                    <input type="hidden" asp-for="UserId" />
                    <div class="row m-3"><h4>Etkinlik Oluştur</h4></div>
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Etkinlik Adı</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="Name" class="form-control form-control-sm" />
                                    <span asp-validation-for="Name"></span>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Başlık</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="Title" class="form-control form-control-sm" />
                                    <span asp-validation-for="Title"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">İl</h6>
                                </div>
                                <div class="col-sm-9">
                                    <select asp-for="City" class="form-control form-control-sm" asp-items="cities">
                                    </select>
                                    <span asp-validation-for="City"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">İlçe</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="State" class="form-control form-control-sm" />
                                    <span asp-validation-for="State"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Adres</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="AddressDetail" class="form-control form-control-sm" />
                                    <span asp-validation-for="AddressDetail"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Etkinlik Tarihi</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="ActivityDate" class="form-control form-control-sm" />
                                    <span asp-validation-for="ActivityDate"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Fotoğraf</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="PictureUrl" class="form-control form-control-sm" />
                                    <span asp-validation-for="PictureUrl"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Açıklama</h6>
                                </div>
                                <div class="col-sm-9">
                                    <input asp-for="Definition" class="form-control" />
                                    <span asp-validation-for="Definition"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-9">
                        <input class="btn btn-outline-success" type="submit" name="save" value="Kaydet" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

eGonullu/Views/MyActivities/Index.cshtml
@model eGonullu.ViewModels.ActivityIndexViewModel
@{
    ViewBag.Title = "Etkinliklerim";
}

<div class="jumbotron">
    <h4 class="display-3">Etkinliklerim</h4>
    <p class="lead">
        Etkinlikleriniz bu alanda yer alır.
    </p>
</div>

<div class="row row-cols-1 row-cols-md-5 m-3">
    @if (Model.Activities.Any())
    {
        @foreach (var activity in Model.Activities)
        {
                
            <div class="card p-1" style="width: 18rem;">
                <img src="@activity.PictureUrl" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@activity.Name</h5>
                    <p class="card-text">
                        @activity.Definition
                    </p>
                    <p class="card-text"><small class="text-muted">Etkinliğe Kalan Süre: @((activity.ActivityDate-DateTime.Now).Hours) saat</small></p>
                    <a asp-action="Details" asp-controller="MyActivities" asp-route-id="@activity.Id"  class="btn btn-outline-success btn-sm btn-block">İncele</a>
                </div>
            </div>
        }
    }

</div>